package remote

import (
	"fmt"
	"strings"
)

// ComposeTemplate is the compose file Sail writes for an app.
//
// It resolves ${APP_IMAGE}:${APP_TAG}, both supplied via the env files Sail passes on every
// compose call. Secrets are not here: they come from .env on the server.
//
// The healthcheck is what `up -d --wait` gates on, so rollback depends on it. An app
// scaffolded without one still deploys, but verification only confirms it started.
func ComposeTemplate(app string, port int) string {
	if port == 0 {
		port = 8080
	}

	var b strings.Builder
	b.WriteString("# Generated by sail app new. Edit freely; Sail only pins the image tag.\n")
	// name: matches the app name so containers and networks are namespaced per app.
	fmt.Fprintf(&b, "name: %s\n\n", app)
	b.WriteString("services:\n")
	fmt.Fprintf(&b, "  %s:\n", app)
	b.WriteString("    image: ${APP_IMAGE}:${APP_TAG}\n")
	b.WriteString("    restart: unless-stopped\n")
	b.WriteString("    env_file:\n")
	b.WriteString("      - .env\n")
	b.WriteString("    ports:\n")
	fmt.Fprintf(&b, "      - \"%d:%d\"\n", port, port)
	b.WriteString("    healthcheck:\n")
	b.WriteString("      # Required for rollback: `up -d --wait` blocks on this and exits non-zero if it never passes.\n")
	b.WriteString("      test: [\"CMD-SHELL\", \"wget -q -O /dev/null http://127.0.0.1:")
	fmt.Fprintf(&b, "%d/health || exit 1\"]\n", port)
	b.WriteString("      interval: 5s\n")
	b.WriteString("      timeout: 3s\n")
	b.WriteString("      retries: 5\n")
	b.WriteString("      start_period: 20s\n")
	return b.String()
}

// WriteFileScript writes stdin to a path, creating it 600.
//
// Content is piped over stdin rather than embedded in the command: a compose file holds
// newlines and shell metacharacters, and interpolating it would be an injection risk.
func WriteFileScript(path string) string {
	return fmt.Sprintf("umask 077 && cat > %s && chmod 600 %s", Quote(path), Quote(path))
}

// MkdirScript creates a directory 700.
func MkdirScript(dir string) string {
	return fmt.Sprintf("mkdir -p %s && chmod 700 %s", Quote(dir), Quote(dir))
}

// EnsureEnvScript creates an empty .env only if absent, so secrets are never clobbered.
func EnsureEnvScript(path string) string {
	return fmt.Sprintf("test -f %s || (umask 077 && : > %s && chmod 600 %s)",
		Quote(path), Quote(path), Quote(path))
}

// RemoveAppScript stops the app, then deletes its directory.
//
// Teardown runs before rm so a failure to stop does not delete the files needed to stop it.
func RemoveAppScript(l Layout) string {
	return strings.Join([]string{
		fmt.Sprintf("cd %s 2>/dev/null && docker compose -f %s --env-file %s --env-file %s down --remove-orphans || true",
			Quote(l.Dir()), Quote(l.ComposePath()), Quote(l.EnvPath()), Quote(l.TagEnvPath())),
		fmt.Sprintf("rm -rf %s", Quote(l.Dir())),
	}, " && ")
}
